/** Best-effort IANA zone from ISO-2. City-level TZ is a later geocode concern. */
const COUNTRY_TZ: Record<string, string> = {
  AD: "Europe/Andorra",
  AL: "Europe/Tirane",
  AT: "Europe/Vienna",
  BA: "Europe/Sarajevo",
  BE: "Europe/Brussels",
  BG: "Europe/Sofia",
  BY: "Europe/Minsk",
  CH: "Europe/Zurich",
  CY: "Asia/Nicosia",
  CZ: "Europe/Prague",
  DE: "Europe/Berlin",
  DK: "Europe/Copenhagen",
  EE: "Europe/Tallinn",
  ES: "Europe/Madrid",
  FI: "Europe/Helsinki",
  FO: "Atlantic/Faroe",
  FR: "Europe/Paris",
  GB: "Europe/London",
  GE: "Asia/Tbilisi",
  GI: "Europe/Gibraltar",
  GR: "Europe/Athens",
  HR: "Europe/Zagreb",
  HU: "Europe/Budapest",
  IE: "Europe/Dublin",
  IS: "Atlantic/Reykjavik",
  IT: "Europe/Rome",
  LI: "Europe/Vaduz",
  LT: "Europe/Vilnius",
  LU: "Europe/Luxembourg",
  LV: "Europe/Riga",
  MC: "Europe/Monaco",
  MD: "Europe/Chisinau",
  ME: "Europe/Podgorica",
  MK: "Europe/Skopje",
  MT: "Europe/Malta",
  NL: "Europe/Amsterdam",
  NO: "Europe/Oslo",
  PL: "Europe/Warsaw",
  PT: "Europe/Lisbon",
  RO: "Europe/Bucharest",
  RS: "Europe/Belgrade",
  RU: "Europe/Moscow",
  SE: "Europe/Stockholm",
  SI: "Europe/Ljubljana",
  SK: "Europe/Prague",
  SM: "Europe/San_Marino",
  TR: "Europe/Istanbul",
  UA: "Europe/Kyiv",
  XK: "Europe/Belgrade",
};

export function timezoneForCountry(code: string | null | undefined): string {
  if (!code) return "Europe/Prague";
  return COUNTRY_TZ[code.trim().toUpperCase()] || "Europe/Prague";
}
